
package https.www_ivy;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.0
 * 
 */
@WebService(name = "calapp", targetNamespace = "https://www.ivy.global/")
public interface Calapp {


    /**
     * 
     * @param a
     * @param b
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "addResult", targetNamespace = "")
    @RequestWrapper(localName = "addMethod", targetNamespace = "https://www.ivy.global/", className = "https.www_ivy.AddMethod")
    @ResponseWrapper(localName = "addMethodResponse", targetNamespace = "https://www.ivy.global/", className = "https.www_ivy.AddMethodResponse")
    public int addMethod(
        @WebParam(name = "a", targetNamespace = "")
        int a,
        @WebParam(name = "b", targetNamespace = "")
        int b);

}
